### ISSUE TITLE
🍄 armazenamento de exceções

### ISSUE THREAD

**Issue by naoliv** [simbiose/peabiru#19]
Precisa armazenar os locais que são conhecidamente isolados, para evitar dar mensagens e avisos quando encontrar algum desses (ou mesmo para não calcular rota com eles)

**Comment by leite** [comment]
@naoliv boa ideia, já ta previsto algo do gênero, repare na tabela de **_[reports](https://github.com/simbiose/peabiru/blob/dev/schema.sql#L140)_**, ele associa um **_place_** e idealmente a um **_user_** que por hora não sera necessário.

Sendo assim ele não voltara a calcular conexões ate alguém tratar este problema, por consequência poderá extrair uma lista de **_places_** com **_reports_** em aberto.
