### ISSUE TITLE
🔝 teste de conectividade

### ISSUE THREAD

**Issue by naoliv** [simbiose/peabiru#21]
Usar um `sort by rand()`, usando um timestamp junto, para testar de 100 em 100 localidades
A cada 1 ou 2 minutos testa os top 100 do select

**Comment by leite** [comment]
precisa de uma adequação e mais testes no script, mais considero feito [aqui](https://github.com/simbiose/peabiru/commit/42d973a41d8633a5ca9fa6d8ce327dc5788d5d89) e [ali](https://github.com/simbiose/peabiru/commit/9b89428cbe9c8edde0996514523e90031677b7ac#diff-c1e8702b98792b52aba8016bae4a6f32)
